### ISSUE TITLE
Error in Clean Up Human Player Mode

### ISSUE THREAD

**Issue by DemoreXTess** [rstrivedi/Melting-Pot-Contest-2023#16]
<code>Running an episode with 7 players: ['1', '2', '3', '4', '5', '6', '7'].
Traceback (most recent call last):
  File "/home/tess/Desktop/MARL/contest/meltingpot/human_players/play_clean_up.py", line 91, in <module>
    main()
  File "/home/tess/Desktop/MARL/contest/meltingpot/human_players/play_clean_up.py", line 83, in main
    level_playing_utils.run_episode(
  File "/home/tess/Desktop/MARL/contest/meltingpot/human_players/level_playing_utils.py", line 344, in run_episode
    verbose_fn(timestep, i, player_index)
  File "/home/tess/Desktop/MARL/contest/meltingpot/human_players/play_clean_up.py", line 44, in verbose_fn
    cleaned = env_timestep.observation[f'{lua_index}.PLAYER_CLEANED']
KeyError: '1.PLAYER_CLEANED'</code>

it's only appear when verbose=True

**Comment by duenez** [comment]
You need to also enable debug observations on the clean_up.py config. Unfortunately we don't provide a way to enable these from command line arguments. The reason is because debug observations are expensive, and we don't want to accidentally have them turned on.

**Comment by DemoreXTess** [comment]
Okay then not problem I am closing
